kind: project
metadata:
  name: azureml-demo
spec:
  description: test
  params:
    label_column: label
  functions:
  - url: hub://azureml_utils
    name: train
  artifacts:
  - kind: ''
    target_path: https://s3.wasabisys.com/iguazio/data/iris/iris.data.raw.csv
    key: data
  source: ./
  subpath: ''
  origin_url: ''
  load_source_on_run: true
  desired_state: online
